#!/usr/bin/env node
// Extracts the June suite's real answers into site/src/data/samples.json so the
// website can show a live before/after built from committed transcripts rather
// than a hand-written mock-up.
//
// This is the whole point: the numbers and the prose are the same artefact the
// benchmarks are computed from. Nothing here is written for the website.
//
// Run:  node scripts/build-samples.js          (write)
//       node scripts/build-samples.js --check   (fail if stale; for CI)

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const RAW = path.join(ROOT, 'benchmarks', 'results', 'raw');
const OUT = path.join(ROOT, 'site', 'src', 'data', 'samples.json');

const ARMS = ['vanilla', 'caveman', 'ponytail', 'rdxmin'];
const TASKS = [
  { id: 'cache', kind: 'code', prompt: 'Add a cache layer for our user profile API responses. Show the code.' },
  { id: 'debounce', kind: 'code', prompt: 'Add debounce to a search input that currently fires an API call on every keystroke. Show the code.' },
  { id: 'auth-bug', kind: 'code', prompt: 'Our auth middleware rejects valid tokens at the exact expiry boundary (it uses currentTime > expiry). Find and fix the root cause.' },
  { id: 'pooling', kind: 'prose', prompt: 'Explain how database connection pooling works and why it helps.' },
  { id: 'rest-graphql', kind: 'prose', prompt: 'Summarize the main tradeoffs between REST and GraphQL for a new API.' },
  { id: 'regex-concept', kind: 'prose', prompt: 'Explain what a regular expression backreference is, with one short example.' },
];

// Long answers are truncated for the page, but the token count always reflects
// the FULL billed response — truncating the text and then quoting a shrunken
// number would misreport the thing being measured.
const MAX_CHARS = 1400;

function cell(task, arm) {
  const p = path.join(RAW, `${task}__${arm}.json`);
  let d;
  try { d = JSON.parse(fs.readFileSync(p, 'utf8')); } catch (_) { return null; }
  if (!d || d.is_error) return null;
  const full = (d.result || '').trim();
  const truncated = full.length > MAX_CHARS;
  return {
    tokens: d.usage.output_tokens,
    lines: full ? full.split('\n').length : 0,
    chars: full.length,
    truncated,
    text: truncated ? full.slice(0, MAX_CHARS) : full,
  };
}

function build() {
  const tasks = [];
  for (const t of TASKS) {
    const arms = {};
    for (const a of ARMS) {
      const c = cell(t.id, a);
      if (c) arms[a] = c;
    }
    if (arms.vanilla && arms.rdxmin) tasks.push({ ...t, arms });
  }
  return JSON.stringify({
    note: 'Generated by scripts/build-samples.js from benchmarks/results/raw/. Do not edit by hand.',
    suite: 'June 4-arm suite, Haiku, isolated configs; arms differ only in the injected system prompt.',
    tasks,
  }, null, 2) + '\n';
}

function main() {
  const json = build();
  if (process.argv.includes('--check')) {
    let have = '';
    try { have = fs.readFileSync(OUT, 'utf8'); } catch (_) {}
    if (have !== json) {
      console.error('site/src/data/samples.json is stale. Run: node scripts/build-samples.js');
      process.exit(1);
    }
    console.log('samples.json in sync.');
    return;
  }
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, json);
  const n = JSON.parse(json).tasks.length;
  console.log(`wrote ${path.relative(ROOT, OUT)} — ${n} tasks`);
}

main();
